// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBijp_LiSJENzFxpCaddS3VkUQgxWi_48g',
    appId: '1:124223291911:web:b2e9546d7963f6c52d20a2',
    messagingSenderId: '124223291911',
    projectId: 'project-x-443322',
    authDomain: 'project-x-443322.firebaseapp.com',
    storageBucket: 'project-x-443322.appspot.com',
    measurementId: 'G-0Q0R214TQK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCNJ45kzuTmAqEYP0IqHkPuiS_tgirzO4',
    appId: '1:124223291911:android:89f68ff1880e1bc12d20a2',
    messagingSenderId: '124223291911',
    projectId: 'project-x-443322',
    storageBucket: 'project-x-443322.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcZV6LYu7sfBokn9l0mTRL3URZqakdqWc',
    appId: '1:124223291911:ios:55b8a1d2fd8f64c42d20a2',
    messagingSenderId: '124223291911',
    projectId: 'project-x-443322',
    storageBucket: 'project-x-443322.appspot.com',
    iosBundleId: 'com.example.projectXAdminApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcZV6LYu7sfBokn9l0mTRL3URZqakdqWc',
    appId: '1:124223291911:ios:f5f5e786876614e22d20a2',
    messagingSenderId: '124223291911',
    projectId: 'project-x-443322',
    storageBucket: 'project-x-443322.appspot.com',
    iosBundleId: 'com.example.projectXAdminApp.RunnerTests',
  );
}
